# Generated by Django 4.0.4 on 2022-06-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialn', models.CharField(default='None', max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code')),
            ],
        ),
    ]
