# Generated by Django 4.0.4 on 2022-06-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrc',
            name='serialn',
        ),
    ]
