# Generated by Django 4.0.4 on 2022-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0002_remove_qrc_serialn'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrc',
            name='serialn',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
