# Generated by Django 4.0.4 on 2022-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0003_qrc_serialn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrc',
            name='qr_code',
            field=models.FileField(upload_to='qrcode'),
        ),
        migrations.AlterField(
            model_name='qrc',
            name='serialn',
            field=models.CharField(max_length=100),
        ),
    ]
