# Generated by Django 4.0.4 on 2022-07-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail',
        ),
        migrations.AlterField(
            model_name='user',
            name='centre',
            field=models.TextField(default='', verbose_name='centre'),
        ),
    ]
