# Generated by Django 4.0.6 on 2022-08-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_remove_user_mail_alter_user_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/STUDENTS PAGE/images/'),
        ),
    ]
