# Generated by Django 4.0.6 on 2022-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default='', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(default='', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.TextField(default='', max_length=30, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.TextField(default='', max_length=30, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.TextField(default='', max_length=6, verbose_name='pincode'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(default='', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=30, verbose_name='email'),
        ),
    ]
