# Generated by Django 4.0.6 on 2022-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_remove_user_centre_remove_user_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default='', verbose_name='fpass'),
        ),
    ]
