# Generated by Django 4.0.6 on 2022-08-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_remove_user_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.TextField(default='', verbose_name='fpass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
