# Generated by Django 4.0.6 on 2022-08-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_user_cpassword_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
