# Generated by Django 4.0.6 on 2022-08-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
