# Generated by Django 4.0.6 on 2022-08-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_remove_user_city_remove_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.TextField(default='', verbose_name='center'),
        ),
    ]
