# Generated by Django 4.0.6 on 2022-08-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_user_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='center',
        ),
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(default='', max_length=200, verbose_name='email_token'),
        ),
    ]
