# Generated by Django 4.0.6 on 2022-08-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_remove_user_center_user_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.TextField(default='', verbose_name='center'),
        ),
    ]
