# Generated by Django 4.0.4 on 2022-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appno', models.CharField(default='', max_length=30)),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=30)),
                ('contact', models.IntegerField(default='0000000000')),
                ('center', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
