# Generated by Django 4.0.6 on 2022-08-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studata',
            name='answerid',
        ),
    ]
