# Generated by Django 4.0.6 on 2022-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studata',
            name='id',
        ),
        migrations.AddField(
            model_name='studata',
            name='answerid',
            field=models.TextField(default='', primary_key=True, serialize=False, verbose_name='answerid'),
        ),
        migrations.AddField(
            model_name='studata',
            name='marks',
            field=models.TextField(default='', max_length=3, verbose_name='marks'),
        ),
    ]
