# Generated by Django 4.0.4 on 2022-06-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studata',
        ),
    ]
