# Generated by Django 4.0.6 on 2022-08-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studata_id_studata_answerid_studata_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studata',
            name='answerid',
            field=models.TextField(default='', verbose_name='answerid'),
        ),
    ]
