# Generated by Django 4.0.6 on 2022-08-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studata_answerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='remarks',
            field=models.TextField(default='', verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='studata',
            name='marks',
            field=models.IntegerField(default='', max_length=3, verbose_name='marks'),
        ),
    ]
