# Generated by Django 4.0.4 on 2022-06-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='dob',
            field=models.DateField(default='2001-1-1'),
        ),
    ]
