# Generated by Django 4.0.6 on 2022-08-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studata_remarks_alter_studata_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studata',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='studata',
            name='remarks',
        ),
    ]
