# Generated by Django 4.0.4 on 2022-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studata_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='appno',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studata',
            name='center',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studata',
            name='firstname',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studata',
            name='lastname',
            field=models.TextField(default='', max_length=30),
        ),
    ]
