# Generated by Django 4.0.6 on 2022-08-19 11:14

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studata_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.path_and_rename),
        ),
    ]
