# Generated by Django 4.0.6 on 2022-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studata_marks_remove_studata_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='marks',
            field=models.TextField(default='', max_length=3, verbose_name='marks'),
        ),
        migrations.AddField(
            model_name='studata',
            name='remarks',
            field=models.TextField(default='', verbose_name='remarks'),
        ),
    ]
