# Generated by Django 4.0.4 on 2022-06-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studata_appno_alter_studata_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='dob',
            field=models.DateField(default='2001-1-1', verbose_name='dob'),
        ),
    ]
