# Generated by Django 4.0.6 on 2022-08-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studata_marks_studata_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='marks',
            field=models.IntegerField(default='', max_length=3, verbose_name='marks'),
        ),
    ]
