# Generated by Django 4.0.4 on 2022-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studata_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='dob',
            field=models.DateField(default=''),
        ),
    ]
