# Generated by Django 4.0.6 on 2022-08-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studata_center'),
        ('student', '0008_alter_studata_marks'),
    ]

    operations = [
    ]
