# Generated by Django 4.0.6 on 2022-08-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_merge_0007_studata_center_0008_alter_studata_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='astatus',
            field=models.BooleanField(default=False, verbose_name='astatus'),
        ),
    ]
