# Generated by Django 4.0.4 on 2022-07-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_studata_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='appno',
            field=models.TextField(default='', max_length=30, verbose_name='appno'),
        ),
        migrations.AlterField(
            model_name='studata',
            name='center',
            field=models.TextField(default='', max_length=30, verbose_name='center'),
        ),
        migrations.AlterField(
            model_name='studata',
            name='contact',
            field=models.TextField(default='', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='studata',
            name='dob',
            field=models.DateField(default='2001-1-1', verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='studata',
            name='email',
            field=models.EmailField(default='', max_length=30, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='studata',
            name='firstname',
            field=models.TextField(default='', max_length=30, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='studata',
            name='lastname',
            field=models.TextField(default='', max_length=30, verbose_name='last_name'),
        ),
    ]
