# Generated by Django 4.0.4 on 2022-07-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_studata_appno_alter_studata_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='image',
            field=models.ImageField(default='', upload_to='STUDENTS PAGE/images/'),
        ),
    ]
