# Generated by Django 4.0.4 on 2022-07-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='image',
            field=models.ImageField(default='', upload_to='static/STUDENTS PAGE/images/'),
        ),
    ]
