# Generated by Django 4.0.6 on 2022-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_studata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='city',
            field=models.TextField(default='', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='studata',
            name='country',
            field=models.TextField(default='', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='studata',
            name='password1',
            field=models.TextField(default='', verbose_name='pass1'),
        ),
        migrations.AddField(
            model_name='studata',
            name='password2',
            field=models.TextField(default='', verbose_name='pass2'),
        ),
        migrations.AddField(
            model_name='studata',
            name='pincode',
            field=models.TextField(default='', max_length=6, verbose_name='pincode'),
        ),
        migrations.AddField(
            model_name='studata',
            name='state',
            field=models.TextField(default='', verbose_name='state'),
        ),
    ]
