# Generated by Django 4.0.6 on 2022-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studata_city_studata_country_studata_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studata',
            name='lastname',
        ),
        migrations.AddField(
            model_name='studata',
            name='gender',
            field=models.TextField(default='', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='studata',
            name='pincode',
            field=models.TextField(default='', max_length=6, verbose_name='pin'),
        ),
    ]
