# Generated by Django 4.0.6 on 2022-08-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_studata_lastname_studata_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studata',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='studata',
            name='password2',
        ),
        migrations.AddField(
            model_name='studata',
            name='adress1',
            field=models.TextField(default='', verbose_name='ad1'),
        ),
        migrations.AddField(
            model_name='studata',
            name='adress2',
            field=models.TextField(default='', verbose_name='ad2'),
        ),
        migrations.AddField(
            model_name='studata',
            name='landmark',
            field=models.TextField(default='', verbose_name='ld_mark'),
        ),
        migrations.AddField(
            model_name='studata',
            name='password',
            field=models.TextField(default='', verbose_name='pass'),
        ),
    ]
