# Generated by Django 4.0.6 on 2022-08-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_studata_password1_remove_studata_password2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studata',
            old_name='firstname',
            new_name='fullname',
        ),
    ]
