# Generated by Django 4.0.6 on 2022-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_remove_studata_adress1_remove_studata_adress2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='username',
            field=models.TextField(default='', max_length=10, verbose_name='username'),
        ),
    ]
