# Generated by Django 4.0.6 on 2022-08-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_studata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studata',
            name='password',
        ),
    ]
