# Generated by Django 4.0.6 on 2022-08-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_remove_studata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studata',
            name='aid',
            field=models.TextField(default='', verbose_name='aid'),
        ),
    ]
